Remove uninitialized var warnings present if -O2 is used.
Do it by initializing relevant vars to 0.

houdini_html_e.c: In function ‘houdini_escape_html0’:
houdini_html_e.c:72:11: error: ‘esc’ may be used uninitialized
                        in this function [-Werror=uninitialized]

houdini_xml_e.c: In function ‘houdini_escape_xml’:
houdini_xml_e.c:134:10: error: ‘code’ may be used uninitialized
                        in this function [-Werror=uninitialized]